Repository aUnicornDev/tabsMonster, pull requests merged in 2021-11, with the labels that each got.

#41 Add Star Wars theme
  THEMES.md
Labels: enhancement, good first issue, hacktoberfest-accepted

#43 Create greetings.yml
  .github/workflows/greetings.yml
Labels: documentation, enhancement

#44 tabsMonster tab done
  tabsMonster-chrome/background.js
  tabsMonster-chrome/css/style.css
  tabsMonster-chrome/img/1x/baseline_lock_black_18dp.png
  tabsMonster-chrome/img/baseline_lock_black_18dp.png
  tabsMonster-chrome/img/navbar-1.png
  tabsMonster-chrome/img/navbar-2.png
  tabsMonster-chrome/img/navbar-3.png
  tabsMonster-chrome/img/stats.png
  tabsMonster-chrome/img/theme_pic.jpg
  tabsMonster-chrome/img/theme_pic.png
  tabsMonster-chrome/popup.html
  tabsMonster-chrome/popup.js
Labels: enhancement
